// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * File generators for `db pull`. Each returns the full text of one generated
 * artifact, composed from the fixed template literals in `./templates.ts` plus
 * per-table / conditional fragments built here. No `out +=` accumulation: fixed
 * content is a static template, dynamic content is `.map(...).join('')`.
 *
 * @module
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { IntrospectionResult, TableInfo } from './types.js';
import { camelCase, capitalize, pascalCase, pgTypeToTs, resolveSingular } from './naming.js';
import { introspect } from './introspect.js';
import { toSessionPortUrl } from '../migrations/external-migrations.js';
import {
  GUIDE_AUTH_TO_LIMITATIONS,
  GUIDE_USERID_NOTE,
  META_HEADER_PREFIX,
  META_HEADER_SUFFIX,
  TYPES_HEADER,
  WIRING_CRUD_FN,
  WIRING_IMPORTS,
  WIRING_RESOLVE_CONN_FN,
  WIRING_RESOLVE_SSL_FN,
} from './templates.js';

// ── database.types.ts ──────────────────────────────────────────────────

export function generateTypesFile(tables: TableInfo[]): string {
  const interfaces = tables.map(table => {
    const cols = table.columns.map(col => {
      const tsType = pgTypeToTs(col.data_type);
      const nullable = col.is_nullable === 'YES' ? ' | null' : '';
      return `  ${col.column_name}: ${tsType}${nullable};\n`;
    }).join('');
    // Index signature so this interface satisfies Record<string, unknown>,
    // which is the constraint on db.crud<M>'s row type. Without this,
    // the generated supabase.ts fails typecheck.
    return `export interface ${pascalCase(table.name)} {\n${cols}  [key: string]: unknown;\n}\n\n`;
  }).join('');

  return TYPES_HEADER + interfaces;
}

/**
 * Parse an existing database.meta.ts to extract hand-edited singular values.
 * Returns a map of tableName → singular value from the existing file.
 *
 * Note: the generated file declares `singular` twice per table — once in the
 * runtime `tableMeta` const (the source of truth) and once in the `TableMeta`
 * type mirror. The const is always emitted first, so we keep the FIRST match
 * per table and ignore later ones. This ensures an edit to the runtime const
 * is preserved even if the user did not also edit the type mirror (regeneration
 * rewrites both from the preserved value, restoring consistency).
 *
 * Comments are stripped first so that a commented-out `singular:` note left
 * next to a hand-edit (e.g. `// singular: 'datum'  original`) is not picked
 * up instead of the active value. This is safe because singular values and
 * table keys are identifiers and never contain comment markers.
 */
export function parseExistingMetaSingulars(content: string): Map<string, string> {
  // Strip block and line comments before matching.
  const withoutComments = content
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/[^\n]*/g, '');

  const singulars = new Map<string, string>();
  // Match table entries like: tableName: { singular: 'value', ...
  const re = /^\s+(\w+):\s*\{[^}]*singular:\s*'([^']+)'/gm;
  let match = re.exec(withoutComments);
  while (match !== null) {
    if (!singulars.has(match[1])) {
      singulars.set(match[1], match[2]);
    }
    match = re.exec(withoutComments);
  }
  return singulars;
}

// ── database.meta.ts ───────────────────────────────────────────────────

export function generateMetaFile(tables: TableInfo[], existingSingulars?: Map<string, string>): string {
  const imports = tables.map(t => pascalCase(t.name)).join(', ');

  // Runtime schema. Storage key stays as the actual DB table name (used for SQL).
  // singular/plural are camelCased for use in generated method names. Preserve
  // hand-edited singular values on re-pull (resolveSingular).
  const runtimeEntries = tables.map(table => {
    const singular = resolveSingular(table.name, existingSingulars);
    const plural = camelCase(table.name);
    const primaryKey = Array.isArray(table.primaryKey)
      ? `[${table.primaryKey.map(c => `'${c}'`).join(', ')}]`
      : `'${table.primaryKey}'`;
    const columns = table.columns.map(c => `'${c.column_name}'`).join(', ');
    const autoGenerated = table.autoGenerated.map(c => `'${c}'`).join(', ');
    return `  ${table.name}: {\n` +
      `    singular: '${singular}',\n` +
      `    plural: '${plural}',\n` +
      `    primaryKey: ${primaryKey},\n` +
      `    columns: [${columns}],\n` +
      `    autoGenerated: [${autoGenerated}],\n` +
      `  },\n`;
  }).join('');

  // Type-level mirror.
  const typeEntries = tables.map(table => {
    const singular = resolveSingular(table.name, existingSingulars);
    const plural = camelCase(table.name);
    const autoGen = table.autoGenerated.map(c => `'${c}'`).join(' | ') || 'never';
    return `  ${table.name}: { row: ${pascalCase(table.name)}; singular: '${singular}'; plural: '${plural}'; autoGenerated: ${autoGen} };\n`;
  }).join('');

  return META_HEADER_PREFIX + imports + META_HEADER_SUFFIX +
    'export const tableMeta = {\n' + runtimeEntries + '} as const;\n\n' +
    'export type TableMeta = {\n' + typeEntries + '};\n';
}


// ── database.ca.ts (generated, regenerated each pull) ──────────────────

/**
 * Emit `database.ca.ts` exporting the project's CA certificate as a string
 * constant. The CA is a public, non-secret cert (it contains only a public key
 * and issuer metadata) used by `resolveDbSsl()` to verify the database's TLS
 * server identity. It is committed and bundled into the deployed function, and
 * regenerated on every `db pull` so a rotated CA is picked up. Empty when the
 * caller did not provide a CA (the wiring then falls back to an unverified,
 * encrypted connection — see MIGRATION_GUIDE.md).
 */
export function generateCaFile(caPem?: string): string {
  const header =
    `// Generated by \`db pull\` — safe to regenerate.\n` +
    `// Your database provider's CA certificate (a public, non-secret cert used to\n` +
    `// verify the database's TLS server identity). Refreshed on each \`db pull\`.\n` +
    `// Empty until you provide your CA — see MIGRATION_GUIDE.md (Securing the connection).\n\n`;
  // PEM is plain base64 + delimiters (no backticks/backslashes); escape defensively
  // so an unexpected character can never break out of the template literal.
  const safe = (caPem ?? '').trim().replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return header + 'export const DATABASE_CA_CERT = `' + safe + '`;\n';
}

// ── supabase.ts (generated wiring file) ────────────────────────────────

/**
 * Decide whether `db pull` should (re)write `database.ca.ts`, given the CA the
 * caller supplied (if any) and whether the file already exists.
 *
 * - A CA was provided → write it (also refreshes a rotated CA).
 * - No CA + file missing → write the empty stub so the wiring's import resolves.
 * - No CA + file exists → **preserve** it (return `null`), so a routine re-pull
 *   (e.g. refreshing types after a schema change) does not silently downgrade a
 *   previously-verified app to unverified.
 *
 * Returns the file content to write, or `null` to leave the existing file alone.
 */
export function resolveCaFileWrite(providedCa: string | undefined, fileExists: boolean): string | null {
  if (providedCa !== undefined) return generateCaFile(providedCa);
  if (!fileExists) return generateCaFile();
  return null;
}

export function generateIndexFile(tables: TableInfo[], opts: { projectRef?: string; runtimeConnString: string }): string {
  const hasRls = tables.some(t => t.hasRls);
  const rlsLine = hasRls ? `  rlsPolicy: 'enforce',\n` : '';

  // Parameter name resolution differs by phase:
  //  - At deploy/synth, BLOCKS_STAGE is set, so compute the stage-scoped name
  //    (/blocks/{stage}/db-connection-string). The parameter itself is created+seeded
  //    out-of-band by `ensureSecrets` before deploy (it's the real connection string),
  //    so we use `AppSetting.fromExisting` — CDK does NOT create/seed/tag/delete it,
  //    it only grants the Lambda read access and stamps the name into blocks-config as
  //    BLOCKS_SSM_PARAM_DB_URL (the key is derived from this AppSetting's id 'db-url').
  //  - At Lambda runtime, BLOCKS_STAGE is NOT injected, so recomputing would
  //    wrongly default to 'sandbox' and request a parameter the Lambda has no
  //    grant for (AccessDenied). Instead, read the name CDK already stamped —
  //    loadConfigToProcessEnv() places it in process.env before this module imports.
  const paramBlock =
    `const dbParameterName = process.env.BLOCKS_SSM_PARAM_DB_URL\n` +
    `  ?? dbConnectionParameterName(process.env.BLOCKS_STAGE ?? 'sandbox');\n` +
    `const dbUrl = AppSetting.fromExisting(scope, 'db-url', { name: dbParameterName, secret: true });\n\n`;

  const dbBlock =
    `/**\n` +
    ` * Database instance connected to your Supabase Postgres.\n` +
    ` *\n` +
    ` * RLS caveat: db.crud() (via supabaseCrud()) always enforces RLS.\n` +
    ` * Raw db.query() / db.execute() / db.transaction() BYPASS RLS.\n` +
    ` * For hand-written queries, use db.withRLS({ userId }) to enforce\n` +
    ` * row-level security — otherwise all rows are visible.\n` +
    ` */\n` +
    `export const db = new Database(scope, 'db', {\n` +
    `  connection: fromExisting({ connectionString: { get: resolveConnString }, ssl: resolveDbSsl() }),\n` +
    rlsLine +
    `  schema: tableMeta,\n` +
    `});\n\n`;

  return WIRING_IMPORTS + paramBlock + WIRING_RESOLVE_CONN_FN + WIRING_RESOLVE_SSL_FN + dbBlock + WIRING_CRUD_FN;
}

// ── MIGRATION_GUIDE.md ─────────────────────────────────────────────────

export function generateMigrationGuide(
  tables: TableInfo[],
  nonStandardClaims: Map<string, string[]>,
  existingSingulars?: Map<string, string>,
): string {
  const header =
    `# Migration Guide — Supabase → Blocks\n\n` +
    `Generated by \`db pull\`. Your tables: ${tables.map(t => t.name).join(', ')}\n\n` +
    `> **Scope:** This migration covers the database layer only (tables, types, CRUD, RLS).\n` +
    `> Supabase Auth, Storage, Realtime, and Edge Functions are not migrated.\n\n` +
    `## Query Pattern Mapping\n\n` +
    `| Supabase | Blocks |\n` +
    `|----------|-----|\n`;

  // Method names derive from the same (possibly hand-edited) singular stored in
  // database.meta.ts, so documented api.*X names match the generated ones.
  const rows = tables.map(table => {
    const singular = capitalize(resolveSingular(table.name, existingSingulars));
    const plural = pascalCase(table.name);
    return `| \`supabase.from('${table.name}').select('*')\` | \`api.list${plural}()\` |\n` +
      `| \`.select('id, name')\` | \`api.list${plural}({ select: ['id', 'name'] })\` |\n` +
      `| \`.eq('col', val)\` | \`api.list${plural}({ where: { col: val } })\` |\n` +
      `| \`.gt('col', val)\` | \`api.list${plural}({ where: { col: { gt: val } } })\` |\n` +
      `| \`.order('col', { ascending: false })\` | \`api.list${plural}({ orderBy: ['col:desc'] })\` |\n` +
      `| \`.limit(10)\` | \`api.list${plural}({ limit: 10 })\` |\n` +
      `| \`.single()\` | \`api.get${singular}(id)\` |\n` +
      `| \`.insert({...})\` | \`api.create${singular}({...})\` |\n` +
      `| \`.update({...}).eq('id', x)\` | \`api.update${singular}(x, {...})\` |\n` +
      `| \`.delete().eq('id', x)\` | \`api.delete${singular}(x)\` |\n`;
  }).join('');

  // Conditional: non-standard JWT claims detected in RLS policies.
  let claimsBlock = '';
  if (nonStandardClaims.size > 0) {
    const lines = [...nonStandardClaims].map(
      ([tableName, claims]) => `- **${tableName}**: ${claims.map(c => `\`${c}\``).join(', ')}\n`,
    ).join('');
    claimsBlock =
      `\nDetected non-standard claims in your policies:\n\n` +
      lines +
      `\nConfigure your OIDC provider to include these claims in access tokens.\n`;
  }

  return header + rows + GUIDE_AUTH_TO_LIMITATIONS + claimsBlock + GUIDE_USERID_NOTE;
}

// ── Eligibility + (re)generation helpers ───────────────────────────────

/**
 * Select the tables eligible for Blocks generation: those with a primary key that
 * do not use Supabase Auth (auth.uid()-based RLS). Shared by the full `db pull`
 * and the dev-loop type-refresh path so both agree on what gets generated.
 */
export function selectEligibleTables(intro: IntrospectionResult): TableInfo[] {
  const hasNoPk = (t: TableInfo) => Array.isArray(t.primaryKey) && t.primaryKey.length === 0;
  const isEligible = (t: TableInfo) => !intro.tablesUsingSupabaseAuth.has(t.name) && !hasNoPk(t);
  return intro.tables.filter(isEligible);
}

/**
 * Read hand-edited singular values from an existing `database.meta.ts` so a
 * regeneration preserves them (D6 / PR #787). Returns undefined when the file is
 * absent or unreadable — a permissions/encoding issue degrades to derived
 * singulars with a warning rather than aborting the day-2 loop.
 *
 * Exported for the orchestration + dev-loop regeneration paths; not part of the
 * package's public API (the `db-pull.ts` shim does not re-export it).
 */
export function readExistingSingulars(outputDir: string): Map<string, string> | undefined {
  const metaPath = path.join(outputDir, 'database.meta.ts');
  if (!fs.existsSync(metaPath)) return undefined;
  try {
    return parseExistingMetaSingulars(fs.readFileSync(metaPath, 'utf-8'));
  } catch (err) {
    console.warn(`⚠ Could not read existing database.meta.ts to preserve singulars: ${(err as Error).message}`);
    console.warn(`    Singular names will be regenerated from table names.`);
    return undefined;
  }
}

/**
 * Write ONLY `database.types.ts` + `database.meta.ts` for the given tables into
 * `outputDir`, preserving hand-edited singulars. DB-free (no introspection) so it
 * is directly unit-testable. Deliberately does not write any other file.
 */
export function writeTypesAndMeta(
  outputDir: string,
  tables: TableInfo[],
  existingSingulars?: Map<string, string>,
): void {
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(path.join(outputDir, 'database.types.ts'), generateTypesFile(tables));
  fs.writeFileSync(path.join(outputDir, 'database.meta.ts'), generateMetaFile(tables, existingSingulars));
}

export interface RegenerateTypesResult {
  /** Number of eligible tables written into the generated files. */
  tablesGenerated: number;
  outputDir: string;
}

/**
 * Non-interactive refresh of ONLY `database.types.ts` + `database.meta.ts` from
 * the (already-migrated) external schema, preserving hand-edited singulars.
 *
 * This is the dev-loop "refresh types after applying a migration" primitive
 * (`npm run dev`). It is deliberately narrow: it does **not** prompt, and it does
 * **not** touch `.env.local`, the schema baseline (`000_baseline.sql`),
 * `supabase.ts` (custom code), `MIGRATION_GUIDE.md`, `.gitignore`, or the
 * `index.ts` wiring — all of those are one-time scaffolding owned by the full
 * interactive `db pull`. Regenerating the baseline here would be incorrect: it is
 * the fixed starting schema, and folding applied deltas back into it would corrupt
 * the migration model.
 */
export async function regenerateTypesAndMeta(opts: {
  connectionString: string;
  outputDir: string;
}): Promise<RegenerateTypesResult> {
  // Introspect on the 5432 session port (same as the migrate path), not the 6543
  // transaction pooler — the runtime string stored for dev is 6543.
  // Type-refresh introspection is read-only and dev-loop-scoped (it applies no
  // DDL), so it inherits introspect()'s `allowUnverifiedInCi` tolerance — unlike
  // the migrate step, which fails closed in CI. It also doesn't read the committed
  // database.ca.ts; the operational paths resolve a CA from DATABASE_CA_CERT.
  const intro = await introspect(toSessionPortUrl(opts.connectionString));
  const tables = selectEligibleTables(intro);
  writeTypesAndMeta(opts.outputDir, tables, readExistingSingulars(opts.outputDir));
  return { tablesGenerated: tables.length, outputDir: opts.outputDir };
}
