// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Static, fixed content emitted by the `db pull` generators, as template
 * literals (Option A — no separate `.md`/`.tmpl` assets, so nothing to copy into
 * `dist/`). Only the *invariant* portions live here; per-table and conditional
 * fragments are composed in `./generate.ts`.
 *
 * The migration-guide prose is Supabase-targeted documentation and is
 * intentionally written with Supabase-literal identifiers (e.g. `supabaseCrud`,
 * `Supabase → Blocks`). It is NOT interpolated from `./supabase.ts`: the whole guide
 * becomes provider-supplied when a second provider lands (see supabase.ts / OQ-4),
 * so partially templating only some identifiers now would be inconsistent. The
 * **wiring file** (`WIRING_*`) is different — there the shared identifiers it emits
 * as executable code ARE interpolated from `./supabase.ts` so there is a single
 * definition. If `SUPABASE.crudExportName` ever changes, update the guide prose to
 * match (the `db-pull.test.ts` guide assertions will catch a mismatch).
 *
 * @module
 */
import { SUPABASE } from './supabase.js';

// ── database.types.ts ──────────────────────────────────────────────────

export const TYPES_HEADER = '// Generated by `db pull` — safe to regenerate\n\n';

// ── database.meta.ts ───────────────────────────────────────────────────

export const META_HEADER_PREFIX = '// Generated by `db pull` — safe to regenerate\nimport type { ';
export const META_HEADER_SUFFIX = ' } from \'./database.types.js\';\n\n';

// ── supabase.ts (generated wiring file) ────────────────────────────────

/** Import block + `Scope` declaration. Scope name comes from the provider. */
export const WIRING_IMPORTS = `// Generated by \`db pull\`. Safe to edit — re-pull will not overwrite this file.
import { Database, fromExisting } from '@aws-blocks/bb-data';
import { readFileSync } from 'node:fs';
import { tableMeta, type TableMeta } from './database.meta.js';
import { DATABASE_CA_CERT } from './database.ca.js';
import { Scope } from '@aws-blocks/core';
import { AppSetting } from '@aws-blocks/bb-app-setting';
import { dbConnectionParameterName } from '@aws-blocks/core/db-naming';
import { getStackName } from '@aws-blocks/core/scripts';

const scope = new Scope('${SUPABASE.scopeName}');

`;

/**
 * The runtime port-normalization function (fixed boilerplate).
 *
 * Port policy lives here (the generated, Supabase-aware layer), not in the
 * generic Database BB or the deploy scripts. One stored connection string; the
 * right port is derived per environment so the two can never drift:
 *   - Deployed (`BLOCKS_STACK_NAME` is set by BlocksBackend on the handler): Supavisor
 *     transaction pooler (`:6543`) with prepared statements disabled — required
 *     for connection multiplexing under serverless concurrency.
 *   - Local dev (no `BLOCKS_STACK_NAME`): session port (`:5432`) — the 6543 pooler
 *     is often firewalled on corp dev networks, and one dev process doesn't need
 *     multiplexing.
 * To pin a specific port (e.g. keep `:5432` in production), edit resolveConnString.
 */
export const WIRING_RESOLVE_CONN_FN = `async function resolveConnString(): Promise<string> {
  const raw = await dbUrl.get();
  let u: URL;
  try {
    u = new URL(raw);
  } catch {
    // Not URL-parseable (e.g. an unencoded password) — pg can still parse it.
    // Skip port normalization rather than crash; set the port in your stored
    // connection string if you need a specific one.
    return raw;
  }
  if (process.env.BLOCKS_STACK_NAME) {
    u.port = '6543';
    u.searchParams.set('prepared_statements', 'false');
  } else {
    u.port = '5432';
  }
  // Strip sslmode so resolveDbSsl()'s CA pin takes effect: node pg ignores a
  // programmatic ssl.ca and verifies against the system trust store when
  // sslmode is present in the URL.
  u.searchParams.delete('sslmode');
  return u.toString();
}

`;

/**
 * The TLS-policy function (fixed boilerplate), emitted visibly so the security
 * posture is obvious and editable in your own file rather than hidden in a
 * library default.
 *
 * Supabase's pooler/direct endpoints present a certificate signed by Supabase's
 * private CA, which is NOT in Node's built-in trust store — so verification
 * fails with SELF_SIGNED_CERT_IN_CHAIN unless that CA is pinned. `db pull`
 * captures your project's CA (downloaded from Database Settings → SSL
 * Configuration) into `database.ca.ts` (a public, non-secret cert, refreshed on
 * each pull and bundled into the deployed function). `resolveDbSsl()` pins it,
 * giving a fully verified connection (sslmode=verify-full equivalent).
 *
 * `DATABASE_CA_CERT` (inline PEM or a file path) overrides the committed cert.
 * If neither is available, this falls back to an ENCRYPTED-BUT-UNVERIFIED
 * connection (rejectUnauthorized: false): safe against passive eavesdropping but
 * NOT an active man-in-the-middle. Provide the CA for production.
 */
export const WIRING_RESOLVE_SSL_FN = `function readCaFile(p: string): string {
  // Read a CA file at startup, surfacing a TLS-specific error instead of a bare
  // ENOENT cold-start crash, and reject a file that is not a PEM certificate.
  let pem: string;
  try {
    pem = readFileSync(p, 'utf8');
  } catch (err) {
    throw new Error('[bb-data] DB TLS: could not read the CA at DATABASE_CA_CERT=' + p + ': ' + (err as Error).message + '. See MIGRATION_GUIDE.md.');
  }
  if (!pem.includes('-----BEGIN CERTIFICATE-----')) {
    throw new Error('[bb-data] DB TLS: DATABASE_CA_CERT=' + p + ' is empty or not a PEM certificate (missing -----BEGIN CERTIFICATE-----).');
  }
  return pem;
}

function resolveDbSsl(): { rejectUnauthorized?: true; ca?: string } | { rejectUnauthorized: false } {
  // DATABASE_CA_CERT (inline PEM or a file path) overrides the committed cert.
  // An inline PEM contains the certificate marker; anything else is a file path.
  const envCa = process.env.DATABASE_CA_CERT;
  const ca = envCa
    ? (envCa.includes('-----BEGIN CERTIFICATE-----') ? envCa : readCaFile(envCa))
    : (DATABASE_CA_CERT || undefined);
  if (ca) {
    // Pin the provider CA → fully verified (sslmode=verify-full equivalent). The
    // actual handshake is lazy (first query); bb-data confirms success on connect.
    console.log('[bb-data] DB TLS: will verify the server certificate against the pinned CA on connect (verify-full).');
    return { ca, rejectUnauthorized: true };
  }
  // No CA available. In the deployed function, fail CLOSED rather than connect
  // unverified — a missing CA in production is a misconfiguration, not a default.
  if (process.env.AWS_LAMBDA_FUNCTION_NAME) {
    throw new Error('[bb-data] DB TLS: no CA certificate available (database.ca.ts is empty and DATABASE_CA_CERT is unset) — refusing to connect without verifying the database server certificate. Run bb-data pull to capture your CA, or set DATABASE_CA_CERT. See MIGRATION_GUIDE.md.');
  }
  // ⚠️ Local dev only: encrypted but the server certificate is NOT verified (no
  // man-in-the-middle protection). Download your Supabase CA ('prod-ca-2021.crt'
  // from Database Settings → SSL Configuration) and re-run bb-data pull to capture
  // it (or set DATABASE_CA_CERT). See MIGRATION_GUIDE.md.
  console.warn('[bb-data] DB TLS: server certificate NOT verified — encrypted only (no CA). Run bb-data pull to capture your CA, or set DATABASE_CA_CERT. See MIGRATION_GUIDE.md.');
  return { rejectUnauthorized: false };
}

`;

/**
 * The exported CRUD-spread function. Export name comes from the provider.
 *
 * The table list is derived from `tableMeta` (regenerated on every db pull)
 * rather than hardcoded, so CRUD wiring stays correct when tables are added or
 * removed even though this file is not overwritten on re-pull. The `as` cast
 * preserves the literal-union key type so per-table method types
 * (`api.listX`/`getX`/…) are still generated.
 */
export const WIRING_CRUD_FN = `/** Spread this into your ApiNamespace to add CRUD handlers. */
export function ${SUPABASE.crudExportName}(context: any, auth?: { requireAuth: (ctx: any) => Promise<{ userId: string }> }) {
  return db.crud<TableMeta>({
    tables: Object.keys(tableMeta) as (keyof typeof tableMeta)[],
    auth: () => {
      if (!auth) throw new Error('Auth not configured — pass auth to ${SUPABASE.crudExportName}(). See MIGRATION_GUIDE.md#auth');
      return auth.requireAuth(context);
    },
  });
}
`;

// ── MIGRATION_GUIDE.md ─────────────────────────────────────────────────

/** Fixed prose from `## Auth` through the (fixed) intro of `## Limitations`. */
export const GUIDE_AUTH_TO_LIMITATIONS = `## Auth

\`supabaseCrud()\` requires an \`auth\` argument. Define your auth BB in \`index.ts\` and pass it in:

\`\`\`ts
// index.ts
import { AuthOIDC, google } from '@aws-blocks/bb-auth-oidc';
import { AppSetting } from '@aws-blocks/bb-app-setting';
import { supabaseCrud } from './supabase.js';

const googleId = new AppSetting(scope, 'google-client-id', { name: 'google-client-id' });
const googleSecret = new AppSetting(scope, 'google-secret', { secret: true, name: 'google-client-secret' });
const auth = new AuthOIDC(scope, 'auth', {
  providers: [google({ clientId: () => googleId.get(), clientSecret: () => googleSecret.get() })],
});

export const api = new ApiNamespace(scope, 'api', (context) => ({
  ...supabaseCrud(context, auth),
}));
\`\`\`

AuthOIDC supports Google, Auth0, Clerk, Cognito, and any custom OIDC provider.
See the @aws-blocks/bb-auth-oidc package README for provider setup.

**Migration-specific note:** ensure the \`userId\` your OIDC provider returns matches
the format already stored in your Supabase database (e.g. the \`sub\` claim in your
existing RLS policies). If the format differs, existing users will see zero rows
because RLS policies won't match. Check your \`auth.users\` table to confirm.

The \`userId\` from your auth BB is passed to \`withRLS()\`, which sets
\`request.jwt.claims.sub\` in Postgres. RLS policies using
\`current_setting('request.jwt.claims', true)::jsonb->>'sub'\` work
with any auth provider that returns a stable userId.

**Key rule:** when your auth callback returns \`claims\` (e.g. from Clerk or Auth0),
\`claims.sub\` (the raw provider sub) is what reaches RLS — not the iss-prefixed
\`userId\`. This means existing rows keyed on the raw sub keep matching automatically.

## Verify It Works

1. Add an auth BB to \`index.ts\` and pass it to \`supabaseCrud()\` (see above)
2. Start the dev server: \`npm run dev\`
3. Sign in and call an API method — you should see RLS-filtered results

## Next Steps

1. Update frontend imports: \`supabase.from('x')\` → \`api.listX()\`
2. Override specific methods with \`exclude\` + custom handler if needed

## Connection

You store **one** connection string per environment (in \`.env.local\` for dev/sandbox,
\`.env.production\` for prod). The **port is normalized automatically at runtime** by
\`aws-blocks/supabase.ts\`:

- **In AWS (Lambda):** the Supavisor **transaction pooler (port 6543)** with prepared
  statements disabled — required for connection multiplexing under serverless concurrency.
- **Locally (\`npm run dev\`):** the **session port (5432)** — the 6543 pooler is often
  firewalled on corporate dev networks, and a single dev process doesn't need multiplexing.

So you don't have to get the port right in your env files — paste any valid Supabase
connection string and the right port is applied per environment. To pin a specific port
(e.g. keep 5432 in production), edit \`resolveConnString\` in \`aws-blocks/supabase.ts\`.

## Securing the connection (TLS)

Your connection uses TLS, but the server certificate is **verified only when your
project's CA is pinned**. Supabase's pooler/direct endpoints present a certificate
signed by Supabase's private CA, which isn't in Node's default trust store — so
without it, in local dev \`aws-blocks/supabase.ts\` connects **encrypted but
unverified** (no man-in-the-middle protection), and the **deployed function refuses
to connect** (it fails closed rather than run a privileged workload unverified).

To verify the server identity (recommended, especially for production):

1. Download your CA certificate from the Supabase dashboard:
   **Database Settings → SSL Configuration** (\`prod-ca-2021.crt\`).
2. Capture it by re-running \`npx bb-data pull\` and giving the path when prompted.
   \`db pull\` writes it to \`aws-blocks/database.ca.ts\` (a public, non-secret cert),
   which is committed and bundled into your deployed function — so verification
   works in the deployed Lambda with no extra configuration.

\`resolveDbSsl()\` in \`aws-blocks/supabase.ts\` pins that cert (\`sslmode=verify-full\`
equivalent). \`DATABASE_CA_CERT\` (inline PEM or a file path) overrides it if you
prefer to supply the cert via the environment. Optionally enable **Enforce SSL** in
Database Settings so the server also rejects any non-TLS connection.

> **Upgrading an existing app?** If your \`aws-blocks/supabase.ts\` was generated
> before TLS verification was added, it has no \`resolveDbSsl()\` and connects
> **without verifying the certificate**. Re-running \`npx bb-data pull\` regenerates
> the wiring with verification and prompts for your CA — until you re-pull, the
> existing file stays unverified.

> **Keep \`database.ca.ts\` committed.** It holds a public certificate (no private
> key) and is bundled into your deployed function so verification works there. Do
> not add it to \`.gitignore\`; if it isn't deployed, the deployed function fails
> closed (refuses to connect) rather than running unverified — set
> \`DATABASE_CA_CERT\` if you must supply the CA another way.
>
> **Separate production project?** \`db pull\` captures the CA from the project you
> pulled. If your production database is a different project (recommended) and it
> presents a different CA, re-capture it for production — or set \`DATABASE_CA_CERT\`
> — so verification succeeds against the production server.

## Deploy to Production

\`db pull\` generated \`.env.local\` for local dev. Promote in stages: **local → AWS sandbox → production**.

### 1. (Recommended) Test on an AWS sandbox

\`npm run sandbox\` deploys to a non-production AWS stage and hot-reloads on change, using the connection string in \`.env.local\`. Validate the deployed app here before going to production.

### 2. Set the production database connection string

Production reads \`.env.production\` (or CI environment variables). Create it from the generated example:

\`\`\`sh
cp .env.production.example .env.production
\`\`\`

Set \`SUPABASE_DB_URL\` to your **production** database's connection string. The port is
normalized automatically at runtime (transaction pooler in Lambda), so you don't need to
pick it manually. **Use a separate Supabase project or branch — never your dev database**;
a handler with \`rlsPolicy: 'bypass'\` has full access.

### 3. Set your other production secrets

\`npm run deploy\` provisions **only** the database connection string. Any other secret
your app uses — for example an OIDC client secret — starts as a **random placeholder**
in production and must be given its real value, or that feature (e.g. sign-in) will
fail silently in production with an opaque OIDC error.

**To set the real value** (pick one):

- **\`AppSetting.put()\`** — call at runtime (e.g. in a one-off handler or setup script):
  \`\`\`ts
  // Inside a handler — the AppSetting instance resolves the same SSM parameter
  await mySecret.put('your-real-secret-value');
  \`\`\`
- **AWS CLI** — write directly to the SSM parameter (its name is in your deploy
  output, \`BLOCKS_SSM_PARAM_<ID>\`):
  \`\`\`sh
  aws ssm put-parameter --name "<the BLOCKS_SSM_PARAM_… value from your deploy output>" --type SecureString --value "..." --overwrite
  \`\`\`

The value **persists across redeploys** (the bulk-init uses \`Overwrite: false\`, so it
never clobbers a value you've already set). No redeploy needed after setting — the
Lambda reads the parameter at runtime.

### 4. If you use OAuth (AuthOIDC), register the production callback URL

Add your deployed app's sign-in callback URL to the allowed redirect URIs in your OIDC provider's dashboard (Google/Auth0/Clerk). Sign-in fails with a redirect-mismatch error until this is done. See your auth BB's docs for the exact callback path.

### 5. Deploy

\`\`\`sh
npm run deploy
\`\`\`

\`.env.production\` is gitignored. Your connection string is written to an encrypted SSM SecureString parameter scoped to your app's stack (its name appears in the deploy output as \`BLOCKS_SSM_PARAM_DB_URL\`, e.g. \`/my-app-k7x2mf-prod-db-url\`) — never committed, never placed in the CloudFormation template; the deployed Lambda reads it from SSM at runtime. If you have pending migrations in \`./migrations/\`, they are applied to the production database during deploy (see [Evolving Your Schema](#evolving-your-schema)).

### 6. Verify production

When deploy finishes it prints your live **API URL** and frontend URL (also written to \`.blocks-sandbox/config.json\`). Open the app, sign in, and call an API method — you should see RLS-filtered results, the same as local.

**Rotating the database password:** update \`SUPABASE_DB_URL\` in \`.env.production\` and re-run \`npm run deploy\`. The declared value is written to SSM and wins over any manual, out-of-band edit.

## Adding New Tables

**Important:** As of May 30, 2026, Supabase no longer auto-grants permissions on new
tables ([details](https://github.com/orgs/supabase/discussions/45329)). Every new table
requires an explicit \`GRANT\` before it can be accessed:

\`\`\`sql
GRANT SELECT, INSERT, UPDATE, DELETE ON your_table TO authenticated;
-- For serial/identity columns:
GRANT USAGE, SELECT ON SEQUENCE your_table_id_seq TO authenticated;
\`\`\`

Without this, queries will fail with "permission denied for table".

Once granted, the table is exposed through your API automatically: \`aws-blocks/supabase.ts\`
derives its table list from \`database.meta.ts\`, which is regenerated every time you run a
migration or \`npx bb-data pull\`. You get \`api.<table>.list()\`, \`.get()\`, \`.create()\`, etc.
with no extra wiring.

The one exception: if you have replaced the generated table list in \`aws-blocks/supabase.ts\`
with a fixed array of your own, that array is what's used — add the new table's name to it,
or delete \`supabase.ts\` and re-run \`npx bb-data pull\` to regenerate the automatic wiring.

## Evolving Your Schema

You have two options for changing your schema after \`db pull\`.

**Option 1 — Supabase owns the schema (default during coexistence).**
While you still have \`supabase-js\`/PostgREST clients on this database, change
the schema in Supabase (dashboard or \`supabase\` CLI), then re-run \`npx bb-data pull\`
to refresh \`database.types.ts\` + \`database.meta.ts\`. No migration step.

**Option 2 — Blocks owns the schema (version-controlled migrations).**
Best once you've cut over from PostgREST, or for a database only Blocks uses.
Schema changes become reviewable SQL in your repo and are applied consistently
across environments:

1. Write a numbered migration in \`./migrations\`, e.g. \`migrations/001_add_priority.sql\`:
   \`\`\`sql
   ALTER TABLE tasks ADD COLUMN priority int;
   -- New tables also need a GRANT (see "Adding New Tables" above).
   \`\`\`
2. \`npm run dev\` — applies the pending migration to your **dev** database **and
   refreshes \`database.types.ts\` + \`database.meta.ts\` from the updated schema**, so the
   change is live locally and your code type-checks against it immediately. (It refuses
   if \`.env.local\` points at production. To refresh types by hand at any time, run
   \`npx bb-data pull\`.)
3. Write and test your code locally against the new types before deploying.
4. \`npm run deploy\` — applies the pending migration to **production**, then deploys.
   (\`npm run sandbox\` does the same for a sandbox deploy.)

**Each change is a new file.** A migration is applied exactly once — its filename is
recorded in a \`_migrations\` table and skipped on every later run. So **editing a migration
that has already run does nothing**: the database won't change and your types won't update.
To change the schema again, add the next numbered file (\`002_…\`, \`003_…\`). If you already
edited an applied file by mistake, move your change into a new numbered migration instead.

> Migrations run on the session port (5432), not the 6543 pooler, and are
> serialized with an advisory lock so concurrent deploys don't collide.

> **Do not run \`npx bb-data migrate\` directly for this app** — without \`--url\` it
> targets a local PGlite database your app never uses. \`npm run sandbox\`/\`deploy\`
> apply migrations to the right database automatically. For a one-off, pass
> \`bb-data migrate --url "$SUPABASE_DB_URL" --stage sandbox\`.

### New environments and the schema baseline

\`db pull\` also generates \`migrations/000_baseline.sql\` — your existing schema as
runnable SQL — so a **brand-new, empty** database (a fresh staging env, a CI database,
a teammate's copy) can be built from your migration files alone.

- **Empty database:** the baseline runs first to create the schema, then your other
  migrations apply on top.
- **Your existing database (already has the schema):** the baseline is automatically
  recorded as already-applied and **not** re-run, so nothing is duplicated.

Treat \`000_baseline.sql\` as immutable history — commit it, don't hand-edit it. It is
generated by \`pg_dump\`, so generating/regenerating it requires \`pg_dump\` (PostgreSQL
client tools) on your machine, version >= your database. Applying migrations does **not**
require \`pg_dump\`.

## Troubleshooting

| Symptom | What happened | Fix |
| --- | --- | --- |
| Migration applied, but \`database.types.ts\` / \`database.meta.ts\` didn't update | The schema change is live, but the type refresh after it didn't complete (e.g. a dropped connection). Your code now type-checks against a stale schema. | Run \`npx bb-data pull\` to regenerate the types from the current schema. |
| You changed a migration file and \`npm run dev\` did nothing | That file was already applied; applied migrations never re-run. | Put the change in the next numbered file (\`002_…\`) and run \`npm run dev\` again. |
| \`permission denied for table "…"\` | A new table has no grant for the \`authenticated\` role. | Add the \`GRANT\` from [Adding New Tables](#adding-new-tables). |
| A new table isn't on \`api.…\` | \`aws-blocks/supabase.ts\` was hand-edited to a fixed table list that doesn't include it. | Add the table name to that list, or delete \`supabase.ts\` and run \`npx bb-data pull\`. |
| \`npm run dev\` refused to apply migrations | \`.env.local\` resolves to your **production** database; the dev loop will not run schema changes there. | Point \`.env.local\` at a dev/branch database. (Set \`BLOCKS_SKIP_DEV_MIGRATIONS=1\` only if you intend to skip the dev apply entirely.) Note: this guard is best-effort and **fails open** — if it cannot determine your production database (no \`.env.production\` and no production SSM parameter) it proceeds anyway, so don't rely on it as the only safeguard against pointing \`.env.local\` at production. |
| \`Cannot reach the database on port 5432\` | Migrations use the session port (5432), which a firewall, IP allow-list, or IPv6-only host may block. | Allow your machine/CI egress to reach the host on 5432, or run the migration from a network that can. |
| A migration failed mid-deploy (\`npm run sandbox\` or \`npm run deploy\`) | A forward migration threw an error partway through. Migrations are forward-only (no down/rollback) and advisory-locked, so the partially-applied state persists. | 1. Check the deploy output for the failing SQL statement. 2. Fix the issue (e.g. correct the SQL, add a missing column dependency). 3. If the migration partially applied, write a new numbered migration to bring the schema to the intended state. 4. Re-run \`npm run deploy\`. Do NOT edit the failed migration file — it's already recorded as attempted. |
| \`000_baseline.sql\` fails on a fresh Supabase project (\`42P06\` or \`42501\`) | If you generated the baseline with an older version of \`db pull\`, it may contain platform-specific statements (\`CREATE SCHEMA public\`, \`ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin\`) that a normal connection can't replay. Newer versions of \`db pull\` strip these automatically. | Re-run \`npx bb-data pull\` to regenerate the baseline, or manually remove the offending lines: delete \`CREATE SCHEMA public;\`, delete all \`ALTER DEFAULT PRIVILEGES\` lines, and change \`CREATE FUNCTION\` to \`CREATE OR REPLACE FUNCTION\`. |

## Limitations

- **Public schema only.** \`db pull\` migrates tables in the \`public\` schema. Tables in
  custom schemas are not picked up and won't appear in generated code. Most Supabase
  apps keep everything in \`public\`.

- **Connection pool coexistence.** While your Supabase frontend and Blocks Lambda both
  connect to the same Supabase database (the "strangler fig" coexistence period), they
  share the same connection limits (~200 pooler / ~15 session). High concurrency on
  either side can exhaust the pool for both. Consider setting a Lambda reserved
  concurrency cap below the pooler limit during coexistence.

- **Non-standard JWT claims.** RLS policies that reference JWT claims beyond \`sub\` and \`role\` require your OIDC
  provider to include those claims in the access token. If your policies return zero
  rows after migration, check which claims your RLS policies read and ensure your
  OIDC provider emits them.
`;

/** Fixed trailer (Finding 8 — userId-vs-sub note), appended after the claims block. */
export const GUIDE_USERID_NOTE = `
## Note: User ID Formats

Your migrated tables store the raw provider \`sub\` as the user identifier
(e.g., \`auth0|abc123\`). New tables created with Blocks use \`user.userId\`
by default, which is iss-prefixed (e.g., \`https://tenant.auth0.com/:auth0|abc123\`).

When JOINing migrated tables with new tables, use \`user.claims.sub\` (raw sub)
as the foreign key in new tables for consistency.
`;
