// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Shared `db pull` data types: the introspected schema shape and the options
 * passed through the pull pipeline. Provider-agnostic — nothing here is specific
 * to Supabase (see `./supabase.ts` for provider specifics).
 *
 * @module
 */

export interface ColumnInfo {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default: string | null;
  ordinal_position: number;
}

export interface TableInfo {
  name: string;
  columns: ColumnInfo[];
  primaryKey: string | string[];
  autoGenerated: string[];
  hasRls: boolean;
  /** True if the `authenticated` role is missing SELECT/INSERT/UPDATE/DELETE grants. */
  missingGrants: boolean;
}

export interface IntrospectionResult {
  tables: TableInfo[];
  /** Tables whose RLS policies reference auth.uid() — skipped from migration. */
  tablesUsingSupabaseAuth: Set<string>;
  /** Per-table list of JWT claims referenced in RLS policies (beyond sub/role). */
  nonStandardClaims: Map<string, string[]>;
}

export interface DbPullOptions {
  /** Connection string for introspection (port 5432). */
  connectionString: string;
  /** Output directory for generated files. */
  outputDir: string;
  /** Supabase project ref (for AppSetting parameter naming). */
  projectRef?: string;
  /**
   * PEM contents of the provider's CA certificate (public, non-secret). Written
   * to `database.ca.ts` and pinned by the generated wiring for TLS verification.
   * When omitted, the generated connection falls back to encrypted-but-unverified.
   */
  caCert?: string;
}
