// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { test, describe } from 'node:test';
import assert from 'node:assert';
import {
  generateTypesFile,
  generateMetaFile,
  generateIndexFile,
  generateCaFile,
  resolveCaFileWrite,
  generateMigrationGuide,
  isServerManagedDefault,
  parseExistingMetaSingulars,
  selectEligibleTables,
  writeTypesAndMeta,
  type TableInfo,
  type IntrospectionResult,
} from './db-pull.js';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

// ── Fixtures ───────────────────────────────────────────────────────────

const TABLES: TableInfo[] = [
  {
    name: 'migration_test_todos',
    columns: [
      { table_name: 'migration_test_todos', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: 'gen_random_uuid()', ordinal_position: 1 },
      { table_name: 'migration_test_todos', column_name: 'user_id', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      { table_name: 'migration_test_todos', column_name: 'title', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 3 },
      { table_name: 'migration_test_todos', column_name: 'done', data_type: 'boolean', is_nullable: 'NO', column_default: 'false', ordinal_position: 4 },
      { table_name: 'migration_test_todos', column_name: 'created_at', data_type: 'timestamp with time zone', is_nullable: 'NO', column_default: 'now()', ordinal_position: 5 },
    ],
    primaryKey: 'id',
    autoGenerated: ['id', 'created_at'],
    hasRls: true,
    missingGrants: false,
  },
  {
    name: 'categories',
    columns: [
      { table_name: 'categories', column_name: 'id', data_type: 'serial', is_nullable: 'NO', column_default: "nextval('categories_id_seq'::regclass)", ordinal_position: 1 },
      { table_name: 'categories', column_name: 'name', data_type: 'character varying', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      { table_name: 'categories', column_name: 'metadata', data_type: 'jsonb', is_nullable: 'YES', column_default: null, ordinal_position: 3 },
    ],
    primaryKey: 'id',
    autoGenerated: ['id'],
    hasRls: false,
    missingGrants: false,
  },
];

// ── generateTypesFile ──────────────────────────────────────────────────

describe('generateTypesFile', () => {
  const output = generateTypesFile(TABLES);

  test('produces PascalCase interface names from snake_case tables', () => {
    assert.ok(output.includes('export interface MigrationTestTodos {'));
    assert.ok(output.includes('export interface Categories {'));
  });

  test('maps PG types to TS types correctly', () => {
    assert.ok(output.includes('id: string;'));          // uuid → string
    assert.ok(output.includes('done: boolean;'));       // boolean → boolean
    assert.ok(output.includes('created_at: string;')); // timestamptz → string
    assert.ok(output.includes('metadata: Record<string, unknown> | null;')); // jsonb nullable
  });

  test('includes index signature for Record<string, unknown> compat', () => {
    assert.ok(output.includes('[key: string]: unknown;'));
  });
});

// ── generateMetaFile ───────────────────────────────────────────────────

describe('generateMetaFile', () => {
  const output = generateMetaFile(TABLES);

  test('emits camelCase singular and plural', () => {
    assert.ok(output.includes("singular: 'migrationTestTodo'"));
    assert.ok(output.includes("plural: 'migrationTestTodos'"));
    assert.ok(output.includes("singular: 'category'"));
    assert.ok(output.includes("plural: 'categories'"));
  });

  test('uses actual table name as key (for SQL)', () => {
    assert.ok(output.includes('migration_test_todos: {'));
    assert.ok(output.includes('categories: {'));
  });

  test('includes primaryKey and autoGenerated', () => {
    assert.ok(output.includes("primaryKey: 'id'"));
    assert.ok(output.includes("autoGenerated: ['id', 'created_at']"));
  });

  test('type-level TableMeta includes plural field', () => {
    assert.ok(output.includes("plural: 'migrationTestTodos'"));
    assert.ok(output.includes("plural: 'categories'"));
  });

  test('emits array for composite primaryKey', () => {
    const compositeTable: TableInfo = {
      name: 'enrollments',
      columns: [
        { table_name: 'enrollments', column_name: 'student_id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 1 },
        { table_name: 'enrollments', column_name: 'course_id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      ],
      primaryKey: ['student_id', 'course_id'],
      autoGenerated: [],
      hasRls: false,
      missingGrants: false,
    };
    const out = generateMetaFile([compositeTable]);
    assert.ok(out.includes("primaryKey: ['student_id', 'course_id']"));
  });
});

// ── generateIndexFile ──────────────────────────────────────────────────

describe('generateIndexFile', () => {
  const output = generateIndexFile(TABLES, { projectRef: 'abcdef', runtimeConnString: 'postgresql://x:y@host:6543/postgres' });

  test('generated CRUD does not import a bundled auth Building Block', () => {
    // supabaseCrud receives auth via an optional parameter, so the generated
    // index stays auth-agnostic and must not import any @aws-blocks/bb-auth* block.
    assert.ok(!output.includes('@aws-blocks/bb-auth'));
  });

  test('supabaseCrud accepts optional auth parameter', () => {
    assert.ok(output.includes('supabaseCrud(context: any, auth?:'));
  });

  test('throws helpful error when auth not configured', () => {
    assert.ok(output.includes("Auth not configured"));
  });

  test('includes stage-scoped AppSetting name (ref-independent)', () => {
    assert.ok(output.includes("dbConnectionParameterName(process.env.BLOCKS_STAGE ?? 'sandbox')"));
    assert.ok(output.includes("from '@aws-blocks/core/db-naming'"));
  });

  test('resolves SSM parameter name from blocks-config at runtime (not BLOCKS_STAGE)', () => {
    // At Lambda runtime BLOCKS_STAGE is unset; the name must come from the
    // deploy-stamped BLOCKS_SSM_PARAM_DB_URL or the prod Lambda requests the
    // sandbox parameter and gets AccessDenied.
    assert.ok(output.includes('process.env.BLOCKS_SSM_PARAM_DB_URL'));
    // The deploy-time fallback (?? ...) still computes the stage-scoped name.
    assert.ok(output.includes('?? dbConnectionParameterName('));
  });

  test('derives the connection port per environment at runtime', () => {
    // Port policy lives in the generated Supabase layer, not the Database BB or
    // deploy scripts. One stored string; Lambda → transaction pooler (6543) with
    // prepared statements disabled, local → session port (5432).
    assert.ok(output.includes('async function resolveConnString()'));
    assert.ok(output.includes('process.env.BLOCKS_STACK_NAME'));
    assert.ok(output.includes("u.port = '6543'"));
    assert.ok(output.includes("u.port = '5432'"));
    assert.ok(output.includes("u.searchParams.set('prepared_statements', 'false')"));
    // Database consumes the resolver via the { get } shape, not the AppSetting directly.
    assert.ok(output.includes('fromExisting({ connectionString: { get: resolveConnString }, ssl: resolveDbSsl() })'));
    // A non-URL-parseable string (e.g. unencoded password) must not crash the
    // runtime — fall back to the raw string and let pg parse it.
    assert.ok(output.includes('catch'));
    assert.ok(output.includes('return raw;'));
  });

  test('emits rlsPolicy when tables have RLS', () => {
    assert.ok(output.includes("rlsPolicy: 'enforce'"));
  });

  test('generated wiring verifies TLS by default via CA pinning (visible, editable)', () => {
    // The connection passes an explicit ssl config (resolveDbSsl), so the secure
    // default is visible in the generated file, not hidden in an engine default.
    assert.ok(output.includes('function resolveDbSsl()'));
    assert.ok(output.includes('ssl: resolveDbSsl()'));
    // Primary path: the project CA captured at pull time, committed in database.ca.ts
    // and bundled into the function (works in Lambda — no runtime file/env needed).
    assert.ok(output.includes("import { DATABASE_CA_CERT } from './database.ca.js'"));
    assert.ok(output.includes('DATABASE_CA_CERT'));
    assert.ok(output.includes('rejectUnauthorized: true'));
    // DATABASE_CA_CERT env override (inline PEM or file path).
    assert.ok(output.includes('process.env.DATABASE_CA_CERT'));
    assert.ok(output.includes('readFileSync'));
    // Visible, commented opt-out fallback when no CA is available.
    assert.ok(output.includes('rejectUnauthorized: false'));
    assert.ok(output.includes('prod-ca-2021'));
    // In the deployed function a missing CA must fail closed, not connect unverified.
    assert.ok(output.includes('AWS_LAMBDA_FUNCTION_NAME'));
    assert.ok(output.includes('refusing to connect'));
    // Logs the resolved TLS mode so success isn't silent.
    assert.ok(output.includes('DB TLS: will verify'));
    assert.ok(output.includes('DB TLS: server certificate NOT verified'));
  });

  test('resolveConnString strips sslmode so the pinned CA takes effect', () => {
    assert.ok(output.includes("u.searchParams.delete('sslmode')"));
  });

  test('wires CRUD from tableMeta (data-driven, not a hardcoded list)', () => {
    // Table list is derived from tableMeta so re-pull table changes are picked
    // up without regenerating supabase.ts. The cast preserves per-table types.
    assert.ok(output.includes('tables: Object.keys(tableMeta) as (keyof typeof tableMeta)[]'));
    // No hardcoded table-name literals in the wiring.
    assert.ok(!output.includes("tables: ['migration_test_todos'"));
  });

  test('header states the file is preserved on re-pull (not regenerated)', () => {
    assert.ok(output.includes('re-pull will not overwrite this file'));
    assert.ok(!output.includes('safe to regenerate'));
  });
});

// ── generateCaFile ─────────────────────────────────────────────────────

describe('generateCaFile', () => {
  test('inlines the provided PEM as the DATABASE_CA_CERT constant', () => {
    const pem = '-----BEGIN CERTIFICATE-----\nMIIBexample\n-----END CERTIFICATE-----';
    const out = generateCaFile(pem);
    assert.ok(out.includes('export const DATABASE_CA_CERT = `'));
    assert.ok(out.includes('-----BEGIN CERTIFICATE-----'));
    assert.ok(out.includes('-----END CERTIFICATE-----'));
    assert.ok(out.includes('safe to regenerate'));
  });

  test('emits an empty constant when no CA is provided', () => {
    const out = generateCaFile();
    assert.ok(out.includes('export const DATABASE_CA_CERT = ``;'));
  });

  test('escapes characters that could break out of the template literal', () => {
    const out = generateCaFile('`${evil}\\');
    // backtick, ${ interpolation, and backslash are all escaped.
    assert.ok(out.includes('\\`'), 'backtick escaped');
    assert.ok(out.includes('\\${evil}'), 'interpolation escaped');
    assert.ok(out.includes('\\\\'), 'backslash escaped');
  });
});

// ── resolveCaFileWrite ─────────────────────────────────────────────────

describe('resolveCaFileWrite', () => {
  test('writes the provided CA (first pull or rotation refresh)', () => {
    const pem = '-----BEGIN CERTIFICATE-----\nAAA\n-----END CERTIFICATE-----';
    const out = resolveCaFileWrite(pem, false);
    assert.ok(out !== null);
    assert.ok(out!.includes('AAA'));

    const refreshed = resolveCaFileWrite(pem, true);
    assert.ok(refreshed !== null && refreshed.includes('AAA'));
  });

  test('writes an empty stub on first pull when no CA is provided', () => {
    const out = resolveCaFileWrite(undefined, false);
    assert.ok(out !== null);
    assert.ok(out!.includes('export const DATABASE_CA_CERT = ``;'));
  });

  test('preserves an existing file when no CA is provided (no silent downgrade on re-pull)', () => {
    // Regression guard: a re-pull that skips the CA prompt must NOT overwrite a
    // previously-populated database.ca.ts (which would turn off verification).
    assert.strictEqual(resolveCaFileWrite(undefined, true), null);
  });
});

// ── generateMigrationGuide ─────────────────────────────────────────────

describe('generateMigrationGuide', () => {
  test('documents TLS certificate verification (CA provisioning)', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('Securing the connection (TLS)'));
    assert.ok(output.includes('prod-ca-2021'));
    assert.ok(output.includes('database.ca.ts'));
    assert.ok(output.includes('DATABASE_CA_CERT'));
  });
  test('uses AuthOIDC for the auth example', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('AuthOIDC'));
    assert.ok(!output.includes('AuthCognito'));
    assert.ok(!output.includes('supabase.auth'));
  });

  test('generates camelCase method names in query mapping', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('listMigrationTestTodos'));
    assert.ok(output.includes('createMigrationTestTodo'));
    assert.ok(output.includes('listCategories'));
  });

  test('method names reflect a preserved hand-edited singular', () => {
    // categories' singular hand-edited from 'category' to 'kategorie'
    const output = generateMigrationGuide(TABLES, new Map(), new Map([['categories', 'kategorie']]));
    assert.ok(output.includes('api.createKategorie'));
    assert.ok(output.includes('api.getKategorie'));
    assert.ok(!output.includes('createCategory'));
  });

  test('includes Limitations section', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('## Limitations'));
    assert.ok(output.includes('claims beyond'));
  });

  test('lists detected non-standard claims per table', () => {
    const claims = new Map([['migration_test_todos', ['email', 'app_metadata']]]);
    const output = generateMigrationGuide(TABLES, claims);
    assert.ok(output.includes('**migration_test_todos**'));
    assert.ok(output.includes('`email`'));
    assert.ok(output.includes('`app_metadata`'));
  });

  test('includes userId-vs-sub note', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('User ID Formats'));
    assert.ok(output.includes('user.claims.sub'));
    assert.ok(output.includes('iss-prefixed'));
  });

  test('includes a Deploy to Production section covering the full rollout', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('## Deploy to Production'));
    // Staged rollout: sandbox rung + production deploy
    assert.ok(output.includes('npm run sandbox'));
    assert.ok(output.includes('npm run deploy'));
    assert.ok(output.includes('.env.production'));
    // Steers customers to a separate prod DB and the 6543 pooler format
    assert.ok(output.includes('never your dev database'));
    assert.ok(output.includes('6543'));
    // Non-DB secrets (e.g. OIDC client secret) are flagged as needing manual setup
    assert.ok(output.includes('random placeholder'));
    assert.ok(output.includes('SSM SecureString'));
    // OAuth callback registration + a way to verify prod
    assert.ok(output.includes('redirect URIs'));
    assert.ok(output.includes('API URL'));
  });
});

// ── Per-table auth.uid() filtering ─────────────────────────────────────

describe('per-table auth.uid() filtering', () => {
  // Simulates a mixed DB: two safe tables + one that uses auth.uid()
  const MIXED_TABLES: TableInfo[] = [
    ...TABLES,
    {
      name: 'profiles',
      columns: [
        { table_name: 'profiles', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: 'gen_random_uuid()', ordinal_position: 1 },
        { table_name: 'profiles', column_name: 'email', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      ],
      primaryKey: 'id',
      autoGenerated: ['id'],
      hasRls: true,
      missingGrants: false,
    },
  ];

  const tablesUsingSupabaseAuth = new Set(['profiles']);
  const filteredTables = MIXED_TABLES.filter(t => !tablesUsingSupabaseAuth.has(t.name));

  test('filtered tables exclude auth.uid() tables', () => {
    assert.strictEqual(filteredTables.length, 2);
    assert.ok(filteredTables.every(t => t.name !== 'profiles'));
  });

  test('generateIndexFile wiring is table-agnostic (exclusion enforced via tableMeta)', () => {
    const output = generateIndexFile(filteredTables, { projectRef: 'abc', runtimeConnString: 'postgresql://x:y@host:6543/postgres' });
    // Wiring derives the table list from tableMeta at runtime, so the index
    // file contains no table-name literals — incompatible tables (e.g. profiles)
    // are excluded by being absent from the regenerated database.meta.ts.
    assert.ok(output.includes('tables: Object.keys(tableMeta) as (keyof typeof tableMeta)[]'));
    assert.ok(!output.includes("'profiles'"));
    assert.ok(!output.includes("'migration_test_todos'"));
  });

  test('generateTypesFile only emits interfaces for migrated tables', () => {
    const output = generateTypesFile(filteredTables);
    assert.ok(output.includes('export interface MigrationTestTodos {'));
    assert.ok(output.includes('export interface Categories {'));
    assert.ok(!output.includes('export interface Profiles {'));
  });

  test('generateMetaFile only emits meta for migrated tables', () => {
    const output = generateMetaFile(filteredTables);
    assert.ok(output.includes('migration_test_todos: {'));
    assert.ok(output.includes('categories: {'));
    assert.ok(!output.includes('profiles: {'));
  });

  test('generateMigrationGuide only documents migrated tables', () => {
    const output = generateMigrationGuide(filteredTables, new Map());
    assert.ok(output.includes('migration_test_todos'));
    assert.ok(output.includes('categories'));
    assert.ok(!output.includes("supabase.from('profiles')"));
  });

  test('generateMigrationGuide documents schema evolution with migrations', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('Evolving Your Schema'), 'has an Evolving Your Schema section');
    assert.ok(output.includes('./migrations'), 'documents the migrations dir convention');
    assert.ok(/npm run sandbox|npm run deploy/.test(output), 'documents the lifecycle apply');
    // The footgun warning: never run bare `bb-data migrate` for an external app.
    assert.ok(output.includes('--url'), 'documents the --url escape hatch / guard');
    assert.ok(/000_baseline\.sql/.test(output), 'documents the schema baseline file');
    assert.ok(/new[- ]?environment|new, empty|brand-new/i.test(output), 'documents building a new environment');
  });

  test('documents the rule that each change is a new migration file (never edit an applied one)', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(/editing a migration[\s\S]*has already run does nothing/i.test(output), 'warns editing an applied migration is a no-op');
    assert.ok(/add the next numbered file|new numbered migration/i.test(output), 'tells the customer to add a new numbered file');
  });

  test('documents how a new table reaches the API and the hand-edited exception', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('database.meta.ts'), 'explains the table list derives from meta');
    assert.ok(/no extra wiring/i.test(output), 'states new tables are auto-wired');
    assert.ok(output.includes('supabase.ts'), 'covers the hand-edited fixed-list case');
  });

  test('includes a Troubleshooting section with concrete recovery steps', () => {
    const output = generateMigrationGuide(TABLES, new Map());
    assert.ok(output.includes('## Troubleshooting'), 'has a Troubleshooting section');
    // Failed type refresh → bb-data pull
    assert.ok(/didn't update[\s\S]*npx bb-data pull/i.test(output), 'recovery for a missed type refresh');
    // Production refusal + reachability
    assert.ok(/refused to apply migrations/i.test(output), 'covers the production-guard refusal');
    assert.ok(/port 5432/.test(output), 'covers the 5432 reachability failure');
  });
});

// ── Supabase Auth detection regex ──────────────────────────────────────

describe('Supabase Auth detection', () => {
  // This is the regex used in introspect() to identify incompatible policies
  const isSupabaseAuthPolicy = (text: string) => /\bauth\.(uid|email|role)\s*\(/.test(text);

  test('detects auth.uid()', () => {
    assert.ok(isSupabaseAuthPolicy('(id = auth.uid())'));
    assert.ok(isSupabaseAuthPolicy('(( SELECT auth.uid() AS uid) = user_id)'));
  });

  test('detects auth.email() and auth.role()', () => {
    assert.ok(isSupabaseAuthPolicy("(email = auth.email())"));
    assert.ok(isSupabaseAuthPolicy("(role = auth.role())"));
  });

  test('does NOT flag auth.jwt() — it is OIDC-compatible', () => {
    assert.ok(!isSupabaseAuthPolicy("(user_id = (auth.jwt() ->> 'sub'::text))"));
    assert.ok(!isSupabaseAuthPolicy("((auth.jwt() -> 'app_metadata'::text) ->> 'role')"));
  });

  test('does NOT flag current_setting-based policies', () => {
    assert.ok(!isSupabaseAuthPolicy("(user_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'sub'))"));
  });
});

// ── Connection string validation ───────────────────────────────────────

describe('connection string URL validation', () => {
  test('valid connection string parses without error', () => {
    assert.doesNotThrow(() => new URL('postgresql://postgres.abc:mypass@db.example.com:5432/postgres'));
  });

  test('unencoded # in password fails URL parsing', () => {
    assert.throws(() => new URL('postgresql://postgres.abc:pass#word@db.example.com:5432/postgres'));
  });

  test('encoded %23 in password parses correctly', () => {
    const url = new URL('postgresql://postgres.abc:pass%23word@db.example.com:5432/postgres');
    assert.strictEqual(url.password, 'pass%23word');
  });
});

// ── Edge cases: no PK and composite PK ─────────────────────────────────

describe('no-PK table', () => {
  const TABLE: TableInfo = {
    name: 'audit_log',
    columns: [
      { table_name: 'audit_log', column_name: 'event_type', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 1 },
      { table_name: 'audit_log', column_name: 'payload', data_type: 'jsonb', is_nullable: 'YES', column_default: null, ordinal_position: 2 },
      { table_name: 'audit_log', column_name: 'created_at', data_type: 'timestamp with time zone', is_nullable: 'NO', column_default: 'now()', ordinal_position: 3 },
    ],
    primaryKey: [], // no PK constraint
    autoGenerated: ['created_at'],
    hasRls: false,
    missingGrants: false,
  };

  test('meta emits empty primaryKey array', () => {
    const output = generateMetaFile([TABLE]);
    assert.ok(output.includes("primaryKey: []"));
  });

  test('types file generates valid interface', () => {
    const output = generateTypesFile([TABLE]);
    assert.ok(output.includes('export interface AuditLog {'));
  });
});

describe('composite PK table', () => {
  const TABLE: TableInfo = {
    name: 'order_items',
    columns: [
      { table_name: 'order_items', column_name: 'order_id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 1 },
      { table_name: 'order_items', column_name: 'product_id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      { table_name: 'order_items', column_name: 'quantity', data_type: 'integer', is_nullable: 'NO', column_default: '1', ordinal_position: 3 },
    ],
    primaryKey: ['order_id', 'product_id'],
    autoGenerated: [],
    hasRls: false,
    missingGrants: false,
  };

  test('meta emits composite primaryKey array', () => {
    const output = generateMetaFile([TABLE]);
    assert.ok(output.includes("primaryKey: ['order_id', 'product_id']"));
  });

  test('generated index lists table for CRUD', () => {
    const output = generateIndexFile([TABLE], { projectRef: 'test', runtimeConnString: 'postgresql://x:y@host:6543/postgres' });
    // The CRUD table list is derived dynamically from tableMeta (PR #787), so it
    // covers every table including composite-PK ones without hardcoding names.
    assert.ok(output.includes('tables: Object.keys(tableMeta) as (keyof typeof tableMeta)[]'));
  });
});

// ── isServerManagedDefault ─────────────────────────────────────────────

describe('isServerManagedDefault', () => {
  test('recognizes system-generation defaults', () => {
    assert.ok(isServerManagedDefault('gen_random_uuid()'));
    assert.ok(isServerManagedDefault('uuid_generate_v4()'));
    assert.ok(isServerManagedDefault('now()'));
    assert.ok(isServerManagedDefault('CURRENT_TIMESTAMP'));
    assert.ok(isServerManagedDefault("nextval('seq'::regclass)"));
  });

  test('recognizes RLS-owner column defaults (session-managed)', () => {
    assert.ok(isServerManagedDefault("(auth.jwt() ->> 'sub'::text)"));
    assert.ok(isServerManagedDefault("auth.uid()"));
    assert.ok(isServerManagedDefault("(current_setting('request.jwt.claims'::text, true)::jsonb ->> 'sub'::text)"));
  });

  test('RLS-owner detection is case-insensitive', () => {
    assert.ok(isServerManagedDefault("AUTH.JWT() ->> 'sub'"));
    assert.ok(isServerManagedDefault("AUTH.UID()"));
    assert.ok(isServerManagedDefault("CURRENT_SETTING('request.jwt.claims'::text, true)"));
  });

  test('does not match partial/unrelated auth mentions', () => {
    assert.ok(!isServerManagedDefault("'auth_token'::text"));
    assert.ok(!isServerManagedDefault("'needs_authorization'::text"));
  });

  test('rejects value-typed defaults', () => {
    assert.ok(!isServerManagedDefault('false'));
    assert.ok(!isServerManagedDefault("'pending'::text"));
    assert.ok(!isServerManagedDefault('0'));
    assert.ok(!isServerManagedDefault("'{}'::jsonb"));
  });

  test('returns false for null', () => {
    assert.ok(!isServerManagedDefault(null));
  });
});

// ── Re-pull preserves hand-edited singulars ────────────────────────────

describe('re-pull preserves hand-edited singulars', () => {
  test('parseExistingMetaSingulars extracts singular values', () => {
    const existing = `// Generated by \`db pull\` — safe to regenerate
import type { Data, Users } from './database.types.js';

export const tableMeta = {
  data: {
    singular: 'dataset',
    plural: 'data',
    primaryKey: 'id',
    columns: ['id', 'value'],
    autoGenerated: ['id'],
  },
  users: {
    singular: 'user',
    plural: 'users',
    primaryKey: 'id',
    columns: ['id', 'name'],
    autoGenerated: ['id'],
  },
} as const;
`;
    const singulars = parseExistingMetaSingulars(existing);
    assert.strictEqual(singulars.get('data'), 'dataset');
    assert.strictEqual(singulars.get('users'), 'user');
  });

  test('ignores a commented-out singular note left below the active value', () => {
    const existing = `export const tableMeta = {
  data: {
    singular: 'dataset',
    // singular: 'datum',  original
    plural: 'data',
  },
} as const;`;
    assert.strictEqual(parseExistingMetaSingulars(existing).get('data'), 'dataset');
  });

  test('ignores a commented-out singular note left above the active value', () => {
    const existing = `export const tableMeta = {
  data: {
    // singular: 'datum',  original
    singular: 'dataset',
    plural: 'data',
  },
} as const;`;
    assert.strictEqual(parseExistingMetaSingulars(existing).get('data'), 'dataset');
  });

  test('returns an empty map for an empty or content-free file', () => {
    assert.strictEqual(parseExistingMetaSingulars('').size, 0);
    assert.strictEqual(parseExistingMetaSingulars('   \n\n\t').size, 0);
    // A header-only / no-table file (e.g. zero eligible tables) also yields nothing.
    assert.strictEqual(parseExistingMetaSingulars('// Generated by `db pull`\nexport const tableMeta = {} as const;\n').size, 0);
  });

  test('ignores a whole table entry commented out with a block comment', () => {
    const existing = `export const tableMeta = {
  /* data: {
    singular: 'datum',
  }, */
  users: {
    singular: 'member',
    plural: 'users',
  },
} as const;`;
    const singulars = parseExistingMetaSingulars(existing);
    assert.strictEqual(singulars.get('users'), 'member');
    assert.strictEqual(singulars.has('data'), false);
  });

  test('generateMetaFile preserves hand-edited singular on re-pull', () => {
    // Simulate: user edited 'data' table singular from 'datum' to 'dataset'
    const tables: TableInfo[] = [{
      name: 'data',
      columns: [
        { table_name: 'data', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: 'gen_random_uuid()', ordinal_position: 1 },
        { table_name: 'data', column_name: 'value', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      ],
      primaryKey: 'id',
      autoGenerated: ['id'],
      hasRls: false,
      missingGrants: false,
    }];

    // Without existing singulars — pluralize generates 'datum'
    const freshOutput = generateMetaFile(tables);
    assert.ok(freshOutput.includes("singular: 'datum'"));

    // With existing singulars — hand-edited 'dataset' is preserved
    const existingSingulars = new Map([['data', 'dataset']]);
    const repullOutput = generateMetaFile(tables, existingSingulars);
    assert.ok(repullOutput.includes("singular: 'dataset'"));
    assert.ok(!repullOutput.includes("singular: 'datum'"));
  });

  test('new tables get fresh singulars even when existing map is provided', () => {
    const tables: TableInfo[] = [
      {
        name: 'data',
        columns: [{ table_name: 'data', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 1 }],
        primaryKey: 'id', autoGenerated: [], hasRls: false, missingGrants: false,
      },
      {
        name: 'tasks',
        columns: [{ table_name: 'tasks', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 1 }],
        primaryKey: 'id', autoGenerated: [], hasRls: false, missingGrants: false,
      },
    ];

    // Only 'data' has an existing override; 'tasks' is new
    const existingSingulars = new Map([['data', 'dataset']]);
    const output = generateMetaFile(tables, existingSingulars);
    assert.ok(output.includes("singular: 'dataset'")); // preserved
    assert.ok(output.includes("singular: 'task'"));    // freshly derived
  });

  // Regression for the double-`singular` footgun: generated meta declares
  // `singular` twice per table (runtime const + type mirror). The parser must
  // preserve the CONST value even when only the const was hand-edited.
  const DATA_TABLE: TableInfo[] = [{
    name: 'data',
    columns: [{ table_name: 'data', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: null, ordinal_position: 1 }],
    primaryKey: 'id', autoGenerated: [], hasRls: false, missingGrants: false,
  }];

  test('parser preserves const edit when only the const block was edited', () => {
    const fresh = generateMetaFile(DATA_TABLE); // both occurrences are 'datum'
    assert.ok(fresh.includes("singular: 'datum'"));
    // Edit ONLY the first occurrence (the runtime tableMeta const)
    const editedConstOnly = fresh.replace("singular: 'datum'", "singular: 'dataset'");
    const parsed = parseExistingMetaSingulars(editedConstOnly);
    assert.strictEqual(parsed.get('data'), 'dataset');
  });

  test('full round-trip through real generator output preserves the edit', () => {
    // 1. fresh generation
    const fresh = generateMetaFile(DATA_TABLE);
    // 2. user edits the singular (both occurrences)
    const edited = fresh.replaceAll("singular: 'datum'", "singular: 'dataset'");
    // 3. parse the edited file
    const parsed = parseExistingMetaSingulars(edited);
    assert.strictEqual(parsed.get('data'), 'dataset');
    // 4. regenerate with preservation — edit survives in BOTH const and type mirror
    const regen = generateMetaFile(DATA_TABLE, parsed);
    assert.ok(regen.includes("singular: 'dataset'"));
    assert.ok(!regen.includes("singular: 'datum'"));
    // and re-parsing the regenerated file is stable
    assert.strictEqual(parseExistingMetaSingulars(regen).get('data'), 'dataset');
  });
});

// ── selectEligibleTables ───────────────────────────────────────────────

describe('selectEligibleTables', () => {
  const noPkTable: TableInfo = {
    name: 'audit_log',
    columns: [{ table_name: 'audit_log', column_name: 'msg', data_type: 'text', is_nullable: 'YES', column_default: null, ordinal_position: 1 }],
    primaryKey: [],
    autoGenerated: [],
    hasRls: false,
    missingGrants: false,
  };

  function intro(tables: TableInfo[], supabaseAuth: string[] = []): IntrospectionResult {
    return {
      tables,
      tablesUsingSupabaseAuth: new Set(supabaseAuth),
      nonStandardClaims: new Map(),
    };
  }

  test('keeps tables with a primary key that do not use Supabase Auth', () => {
    const result = selectEligibleTables(intro(TABLES));
    assert.deepStrictEqual(result.map(t => t.name), ['migration_test_todos', 'categories']);
  });

  test('excludes tables with no primary key', () => {
    const result = selectEligibleTables(intro([...TABLES, noPkTable]));
    assert.ok(!result.some(t => t.name === 'audit_log'));
  });

  test('excludes tables that use Supabase Auth (auth.uid())', () => {
    const result = selectEligibleTables(intro(TABLES, ['migration_test_todos']));
    assert.deepStrictEqual(result.map(t => t.name), ['categories']);
  });
});

// ── writeTypesAndMeta (dev-loop type refresh primitive) ─────────────────

describe('writeTypesAndMeta', () => {
  function tmpDir(): string {
    return fs.mkdtempSync(path.join(os.tmpdir(), 'bb-data-regen-'));
  }

  test('writes ONLY database.types.ts + database.meta.ts and nothing else', () => {
    const dir = tmpDir();
    writeTypesAndMeta(dir, TABLES);
    const written = fs.readdirSync(dir).sort();
    assert.deepStrictEqual(written, ['database.meta.ts', 'database.types.ts']);
    // Must not produce any of the one-time `db pull` scaffolding.
    for (const f of ['.env.local', '.env.production.example', 'supabase.ts', 'MIGRATION_GUIDE.md', 'index.ts']) {
      assert.ok(!fs.existsSync(path.join(dir, f)), `should not write ${f}`);
    }
    assert.ok(!fs.existsSync(path.join(path.dirname(dir), 'migrations', '000_baseline.sql')), 'must not touch the baseline');
  });

  test('content matches the canonical generators', () => {
    const dir = tmpDir();
    writeTypesAndMeta(dir, TABLES);
    assert.strictEqual(fs.readFileSync(path.join(dir, 'database.types.ts'), 'utf-8'), generateTypesFile(TABLES));
    assert.strictEqual(fs.readFileSync(path.join(dir, 'database.meta.ts'), 'utf-8'), generateMetaFile(TABLES));
  });

  test('preserves hand-edited singulars passed in', () => {
    const dir = tmpDir();
    const handEdited = new Map([['categories', 'cat']]);
    writeTypesAndMeta(dir, TABLES, handEdited);
    const meta = fs.readFileSync(path.join(dir, 'database.meta.ts'), 'utf-8');
    assert.ok(meta.includes("singular: 'cat'"), 'uses the hand-edited singular');
    // Round-trips through the parser that the dev loop uses to read it back.
    assert.strictEqual(parseExistingMetaSingulars(meta).get('categories'), 'cat');
  });

  test('re-running into the same dir overwrites without leaving extra files', () => {
    const dir = tmpDir();
    writeTypesAndMeta(dir, TABLES);
    writeTypesAndMeta(dir, [TABLES[0]]);
    assert.deepStrictEqual(fs.readdirSync(dir).sort(), ['database.meta.ts', 'database.types.ts']);
  });
});
