// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Configuration options for the Database Building Block.
 */
import type { ChildLogger } from '@aws-blocks/bb-logger';
export interface DatabaseOptions {
  /** Minimum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  minCapacity?: number;
  /** Maximum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  maxCapacity?: number;
  /** Database name. Derived from scope.fullId if omitted. */
  databaseName?: string;
  /** Wrap an existing database instead of creating one. */
  connection?: ExternalDatabaseRef;
  /** Path to directory containing numbered `.sql` migration files. */
  migrationsPath?: string;
  /** Runtime schema metadata for crud(). Generated by `db pull`. */
  schema?: import('./crud/types.js').TableSchema;
  /**
   * RLS enforcement policy for this database. Set by `db pull` when introspection
   * detects tables with RLS enabled.
   *
   * **Important:** `'enforce'` currently applies ONLY to `db.crud()` operations
   * (which always route through `withRLS()`). Raw `db.query()` / `db.execute()` /
   * `db.transaction()` calls bypass RLS unless you explicitly use
   * `db.withRLS({ userId })`. If you hand-write queries, you must opt in yourself.
   */
  rlsPolicy?: 'enforce';
  /**
   * CloudFormation removal policy for the Aurora cluster.
   * Use 'destroy' for dev/sandbox, 'retain' (default) for production to prevent data loss.
   * @default 'retain'
   */
  removalPolicy?: 'destroy' | 'retain' | 'snapshot';
	/** Optional logger for internal operations. When omitted, a default Logger at error level is created. */
	logger?: ChildLogger;
}

/**
 * Reference to an external database not managed by this Building Block.
 * Used with `Database.fromExisting()`.
 */
export type ExternalDatabaseRef =
  | { host: string; port?: number; database: string; secretArn: string }
  | {
      connectionString: string | { get(): Promise<string> };
      /**
       * TLS settings for the connection. When omitted, the server certificate is
       * **verified by default** (the engine uses `{ rejectUnauthorized: true }`).
       *
       * Managed Postgres providers (Supabase, Neon, RDS) present certificates
       * signed by a provider-specific CA that is not in Node's built-in trust
       * store, so verification requires pinning that CA via `ca`. For Supabase,
       * download `prod-ca-2021.crt` from Database Settings → SSL Configuration.
       *
       * Set `rejectUnauthorized: false` only if you accept the man-in-the-middle
       * risk (encrypted but unauthenticated); prefer pinning the CA instead.
       */
      ssl?: ExternalSslOptions;
    };

/**
 * TLS policy for an external database connection.
 *
 * Modeled as a discriminated union on `rejectUnauthorized` so that a misleading
 * combination is a **compile-time error**: a pinned `ca` is only meaningful when
 * the certificate is actually verified, and node `pg` silently ignores `ca` when
 * `rejectUnauthorized: false`. Expressing `{ ca, rejectUnauthorized: false }` —
 * which looks secure but is not — therefore won't type-check.
 *
 * - `{ rejectUnauthorized?: true; ca?: string }` — verify the server certificate
 *   (the default). Omit `ca` to verify against Node's built-in trust store
 *   (publicly-trusted certs); supply `ca` to pin a provider's private CA.
 * - `{ rejectUnauthorized: false }` — do NOT verify (encrypted but
 *   man-in-the-middle-exposed). A `ca` is not accepted here because it would be ignored.
 */
export type ExternalSslOptions =
  | { rejectUnauthorized?: true; ca?: string }
  | { rejectUnauthorized: false };
