// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * E2E test: db.crud() against a real Supabase database.
 *
 * Tests the full flow:
 *   1. Connect to Supabase via PgClientEngine (port 5432 or 6543)
 *   2. Sign in to Supabase Auth → get JWT
 *   3. db.crud() with auth callback → withRLS → SET LOCAL ROLE
 *   4. Verify CRUD operations with RLS enforcement
 *   5. Verify filter DSL (where, orderBy, limit, select)
 *   6. Verify user isolation (user-2 cannot see user-1 rows)
 *
 * Requires env vars:
 *   SUPABASE_PROJECT_REF, SUPABASE_ANON_KEY, SUPABASE_DB_URL,
 *   SUPABASE_TEST_USER_1_EMAIL, SUPABASE_TEST_USER_1_PASSWORD,
 *   SUPABASE_TEST_USER_2_EMAIL, SUPABASE_TEST_USER_2_PASSWORD
 *
 * Skips gracefully if env vars are not set.
 *
 * Prerequisites on the Supabase project:
 *   - Table `todos` with columns: id (uuid PK default gen_random_uuid()),
 *     user_id (uuid), content (text), done (boolean default false)
 *   - RLS enabled on `todos` with policy using auth.uid() = user_id
 *   - Two auth users (no seed data required — tests create their own)
 */
import { describe, test, before, after } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import { PgClientEngine } from '../engines/pg-client-engine.js';
import { RLSEnabledDatabase } from '../database.js';
import { createCrudHandlers } from './index.js';
import type { TableSchema } from './types.js';

/**
 * SSL for the e2e connections. When `DATABASE_CA_CERT` is set (always in CI — see
 * the e2e-supabase workflow job, which pins the committed Supabase Root CA) the
 * connection runs verify-full, exercising the TLS feature under test. Falls back
 * to unverified only for ad-hoc local runs without a CA.
 */
const E2E_SSL = process.env.DATABASE_CA_CERT
  ? { ca: readFileSync(process.env.DATABASE_CA_CERT, 'utf8'), rejectUnauthorized: true as const }
  : { rejectUnauthorized: false as const };

const env = {
  projectRef: process.env.SUPABASE_PROJECT_REF,
  anonKey: process.env.SUPABASE_ANON_KEY,
  dbUrl: process.env.SUPABASE_DB_URL,
  user1Email: process.env.SUPABASE_TEST_USER_1_EMAIL,
  user1Password: process.env.SUPABASE_TEST_USER_1_PASSWORD,
  user2Email: process.env.SUPABASE_TEST_USER_2_EMAIL,
  user2Password: process.env.SUPABASE_TEST_USER_2_PASSWORD,
};

const skip = !env.projectRef || !env.anonKey || !env.dbUrl || !env.user1Email || !env.user1Password;

let schema: TableSchema;

/** Sign in to Supabase and return the access token + user ID + claims. */
async function signIn(email: string, password: string): Promise<{ token: string; userId: string; claims: Record<string, unknown> }> {
  const url = `https://${env.projectRef}.supabase.co/auth/v1/token?grant_type=password`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'apikey': env.anonKey! },
    body: JSON.stringify({ email, password }),
  });
  if (!res.ok) throw new Error(`Supabase sign-in failed (${res.status}): ${await res.text()}`);
  const data = await res.json() as { access_token: string; user: { id: string } };
  const payload = JSON.parse(Buffer.from(data.access_token.split('.')[1], 'base64url').toString());
  return { token: data.access_token, userId: data.user.id, claims: payload };
}

describe('db.crud() E2E — Supabase', { skip }, () => {
  let engine: PgClientEngine;
  let db: RLSEnabledDatabase;
  let user1: { token: string; userId: string; claims: Record<string, unknown> };
  let user2: { token: string; userId: string; claims: Record<string, unknown> };
  // Seed row IDs — created in before(), cleaned up in after()
  const seedIds: string[] = [];

  before(async () => {
    engine = new PgClientEngine({
      connectionString: env.dbUrl!,
      ssl: E2E_SSL,
    });
    db = new RLSEnabledDatabase(engine);

    // Introspect schema from the live database (mimics db pull)
    const colResult = await engine.query<{ column_name: string; column_default: string | null }>(
      `SELECT column_name, column_default FROM information_schema.columns
       WHERE table_name = 'todos' AND table_schema = 'public' ORDER BY ordinal_position`,
    );
    const columns = colResult.map((r) => r.column_name);
    const autoGenerated = colResult
      .filter((r) => r.column_default !== null)
      .map((r) => r.column_name);

    schema = {
      todos: {
        singular: 'todo',
        plural: 'todos',
        primaryKey: 'id',
        columns,
        autoGenerated,
      },
    };

    user1 = await signIn(env.user1Email!, env.user1Password!);
    user2 = await signIn(env.user2Email!, env.user2Password!);

    // Seed data for both users so list/get/filter tests have rows to work with
    const crud1 = makeCrud(user1);
    const crud2 = makeCrud(user2);
    const s1 = await crud1.createTodo({ user_id: user1.userId, content: 'Seed alpha', done: false });
    const s2 = await crud1.createTodo({ user_id: user1.userId, content: 'Seed beta', done: true });
    const s3 = await crud2.createTodo({ user_id: user2.userId, content: 'Seed gamma', done: false });
    seedIds.push(s1.id, s2.id, s3.id);
  });

  after(async () => {
    // Clean up all seed rows
    if (engine && schema) {
      const crud1 = makeCrud(user1);
      const crud2 = makeCrud(user2);
      for (const id of seedIds) {
        try { await crud1.deleteTodo(id); } catch {}
        try { await crud2.deleteTodo(id); } catch {}
      }
    }
    await engine?.destroy();
  });

  function makeCrud(user: { userId: string; claims: Record<string, unknown> }) {
    return createCrudHandlers(db, schema, {
      tables: ['todos'],
      auth: async () => ({ userId: user.userId, claims: user.claims }),
    });
  }

  test('listTodos returns rows for user-1 only', async () => {
    const crud = makeCrud(user1);
    const rows = await crud.listTodos();
    assert.ok(rows.length > 0, 'Expected at least 1 row for user-1');
    for (const row of rows) {
      assert.strictEqual(row.user_id, user1.userId, 'All rows should belong to user-1');
    }
  });

  test('listTodos with where filter (content equality)', async () => {
    const crud = makeCrud(user1);
    const rows = await crud.listTodos({ where: { content: 'Seed alpha' } });
    assert.ok(rows.length >= 1);
    for (const row of rows) assert.strictEqual(row.content, 'Seed alpha');
  });

  test('listTodos with orderBy', async () => {
    const crud = makeCrud(user1);
    const rows = await crud.listTodos({ orderBy: 'content:asc' });
    for (let i = 1; i < rows.length; i++) {
      assert.ok(rows[i - 1].content <= rows[i].content, 'Should be ordered by content asc');
    }
  });

  test('listTodos with limit', async () => {
    const crud = makeCrud(user1);
    const rows = await crud.listTodos({ limit: 1 });
    assert.strictEqual(rows.length, 1);
  });

  test('listTodos with select', async () => {
    const crud = makeCrud(user1);
    const selectCols = schema.todos.columns.slice(0, 2) as string[];
    const excludedCol = schema.todos.columns[2];
    const rows = await crud.listTodos({ select: selectCols });
    assert.ok(rows.length > 0);
    const keys = Object.keys(rows[0]);
    for (const col of selectCols) assert.ok(keys.includes(col), `Expected ${col} in result`);
    if (excludedCol) assert.ok(!keys.includes(excludedCol), `Expected ${excludedCol} to be absent`);
  });

  test('listTodos with like operator', async () => {
    const crud = makeCrud(user1);
    const rows = await crud.listTodos({ where: { content: { like: 'Seed%' } } });
    assert.ok(rows.length >= 1);
  });

  test('getTodo returns single row', async () => {
    const crud = makeCrud(user1);
    const row = await crud.getTodo(seedIds[0]);
    assert.strictEqual(row.id, seedIds[0]);
    assert.strictEqual(row.content, 'Seed alpha');
  });

  test('getTodo returns null for other user row (RLS)', async () => {
    const crud1 = makeCrud(user1);
    // seedIds[2] belongs to user2
    const row = await crud1.getTodo(seedIds[2]);
    assert.strictEqual(row, null);
  });

  test('createTodo inserts and returns row', async () => {
    const crud = makeCrud(user1);
    const row = await crud.createTodo({ user_id: user1.userId, content: 'E2E crud test', done: false });
    assert.ok(row.id, 'Should have auto-generated id');
    assert.strictEqual(row.content, 'E2E crud test');
    assert.strictEqual(row.user_id, user1.userId);
    seedIds.push(row.id); // clean up in after()
  });

  test('updateTodo updates and returns row', async () => {
    const crud = makeCrud(user1);
    const row = await crud.updateTodo(seedIds[0], { content: 'Seed alpha updated' });
    assert.strictEqual(row.id, seedIds[0]);
    assert.strictEqual(row.content, 'Seed alpha updated');
    // Restore original content for other tests
    await crud.updateTodo(seedIds[0], { content: 'Seed alpha' });
  });

  test('updateTodo returns null for other user row (RLS)', { skip: !env.user2Email }, async () => {
    const crud1 = makeCrud(user1);
    const row = await crud1.updateTodo(seedIds[2], { content: 'hacked' });
    assert.strictEqual(row, null);
  });

  test('deleteTodo deletes own row', async () => {
    const crud = makeCrud(user1);
    // Create a throwaway row to delete
    const tmp = await crud.createTodo({ user_id: user1.userId, content: 'to-delete', done: false });
    const result = await crud.deleteTodo(tmp.id);
    assert.strictEqual(result.deleted, true);
    const row = await crud.getTodo(tmp.id);
    assert.strictEqual(row, null);
  });

  test('deleteTodo cannot delete other user row (RLS)', { skip: !env.user2Email }, async () => {
    const crud1 = makeCrud(user1);
    const result = await crud1.deleteTodo(seedIds[2]);
    assert.strictEqual(result.deleted, false);
  });

  test('user-2 isolation — sees only own rows', { skip: !env.user2Email }, async () => {
    const crud1 = makeCrud(user1);
    const crud2 = makeCrud(user2);
    const user1Rows = await crud1.listTodos();
    const user2Rows = await crud2.listTodos();

    assert.ok(user2Rows.length > 0, 'user-2 should have rows');
    const user1Ids = new Set(user1Rows.map((r: any) => r.id));
    for (const row of user2Rows) {
      assert.ok(!user1Ids.has(row.id), 'user-2 should not see user-1 rows');
      assert.strictEqual(row.user_id, user2.userId);
    }
  });
});
