#!/usr/bin/env node
/**
 * Regenerates the checked-in snapshot files in generated/.
 * Run: npx tsx regenerate-snapshot.ts
 *
 * After running, review the diff and commit alongside your generator changes.
 */
import { generateTypesFile, generateMetaFile, generateIndexFile, generateCaFile } from '../../packages/bb-data/src/db-pull.js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const TABLES = [
  {
    name: 'todos',
    columns: [
      { table_name: 'todos', column_name: 'id', data_type: 'uuid', is_nullable: 'NO', column_default: 'gen_random_uuid()', ordinal_position: 1 },
      { table_name: 'todos', column_name: 'user_id', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      { table_name: 'todos', column_name: 'title', data_type: 'text', is_nullable: 'NO', column_default: null, ordinal_position: 3 },
      { table_name: 'todos', column_name: 'done', data_type: 'boolean', is_nullable: 'NO', column_default: 'false', ordinal_position: 4 },
      { table_name: 'todos', column_name: 'created_at', data_type: 'timestamp with time zone', is_nullable: 'NO', column_default: 'now()', ordinal_position: 5 },
    ],
    primaryKey: 'id',
    autoGenerated: ['id', 'created_at'],
    hasRls: true,
    missingGrants: false,
  },
  {
    name: 'categories',
    columns: [
      { table_name: 'categories', column_name: 'id', data_type: 'serial', is_nullable: 'NO', column_default: "nextval('categories_id_seq'::regclass)", ordinal_position: 1 },
      { table_name: 'categories', column_name: 'name', data_type: 'character varying', is_nullable: 'NO', column_default: null, ordinal_position: 2 },
      { table_name: 'categories', column_name: 'metadata', data_type: 'jsonb', is_nullable: 'YES', column_default: null, ordinal_position: 3 },
    ],
    primaryKey: 'id',
    autoGenerated: ['id'],
    hasRls: false,
    missingGrants: false,
  },
];

const outDir = path.join(__dirname, 'generated');
fs.mkdirSync(outDir, { recursive: true });

fs.writeFileSync(path.join(outDir, 'database.types.ts'), generateTypesFile(TABLES));
fs.writeFileSync(path.join(outDir, 'database.meta.ts'), generateMetaFile(TABLES));
// Sample CA so the generated wiring's `import { DATABASE_CA_CERT }` resolves and
// type-checks. Content is an illustrative placeholder, not a real certificate.
fs.writeFileSync(
  path.join(outDir, 'database.ca.ts'),
  generateCaFile('-----BEGIN CERTIFICATE-----\nMIIBexampleSnapshotCertNotReal==\n-----END CERTIFICATE-----'),
);
fs.writeFileSync(path.join(outDir, 'index.ts'), generateIndexFile(TABLES, { projectRef: 'abcdef', runtimeConnString: 'postgresql://x:y@host:6543/postgres' }));

console.log('✓ Regenerated test-apps/db-pull-typecheck/generated/');
